USE dbColmInventory
GO

SET NOCOUNT ON
GO

ALTER FUNCTION fnMaintenance(@ItemID INTEGER) RETURNS INTEGER
AS
BEGIN
    
    RETURN (SELECT ISNULL(SUM(I.Maintenance), 0) FROM tblInventory AS I WHERE I.ItemID = @ItemID)
	
END
GO
